[build-system]
requires = ["uv_build >= 0.7.19, <0.9.0"]
build-backend = "uv_build"

[project]
name = "dyllibso"
dynamic = ["version"]
description = "Tool for inspecting shared libraries on Linux, MacOS and Windows"
readme = "README.md"
